[package]
name = "server_binary"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.backend_lib]
path = "../backend_lib"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]
