name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Nightly Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features --no-deps -- --deny warnings
    - name: Test
      uses: actions-rs/tarpaulin@v0.1
    - name: Upload code coverage
      uses: codecov/codecov-action@v1