name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.x, 16.x, 17.x] # LTS versions + latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Lint
        run: npm run lint
        working-directory: frontend
